export const ErrorCodes = {
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_MISSING: 'CONFIG_MISSING',
  STARTUP_FAILED: 'STARTUP_FAILED',
  SHUTDOWN_FAILED: 'SHUTDOWN_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};
